name: km_predict
channels:
  - conda-forge
  - main
dependencies:
  - python>=3.5
  - pip
  - pandas
  - scikit-learn
  - scikit-image
  - rasterio
  - netcdf4
  - matplotlib
  - pytest
  - tensorflow-gpu>=2.0.0, <2.6.0
  - keras
